# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdb501bc2c44ed12d895ac846db9c32d0197c8681987167f7c350ad72d60ce0040b6b8825936c3388c1546c2d0401080cea3022d40144764e199bc90d412dff8

test:
  secret_key_base: 2f636cfffcbfb0512d6b9679053dd255679632d47791ae472fda40bf648a14d0a1848cf2be1671ca3940d3bfa56d1c4c191fe2ef0ca8e8675aeddfce7b18a5bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
